site_name: EsiPy
pages:
- Home: 'index.md'
- Getting Started:
    - 'Installation': 'start/installation.md'
    - 'Usage': 'start/usage.md'
- 'SSO Authentication': 'auth.md'
- 'Advanced usage':
    - 'Cache': 'advance/cache.md'
    - 'Signal': 'advance/signal.md'
- About:
    - 'Contact/Contributors': 'about/contact.md'
    - 'Licence': 'about/licence.md'

